### ISSUE TITLE
Type initialization of parameter default values is wrong

### ISSUE THREAD

**Issue by jettan** [delftrobotics/dr_ensenso#11]
https://github.com/fizyr/dr_ensenso/blob/master/dr_ensenso_node/src/ensenso.cpp#L198
`		double calibration_timer_rate = dr::getParam(handle(), "calibration_timer_rate", -1);
`

https://github.com/fizyr/dr_ensenso/blob/master/dr_ensenso_node/src/ensenso.cpp#L204
`		double publish_images_rate = dr::getParam(handle(), "publish_images_rate", 30);
`

`-1` should be `-1.0`
and `30` should be `30.0` because of template matching during compile time in `dr::getParam()`

Current behavior is that both are initialized to integer types.

**Comment by de-vri-es** [comment]
Good point. Could you submit a PR?
