### ISSUE TITLE
Parameter ignore_calibration in DetectCalibrationPattern service is ignored.

### ISSUE THREAD

**Issue by jettan** [delftrobotics/dr_ensenso#2]
https://github.com/delftrobotics/dr_ensenso/blob/master/dr_ensenso_msgs/srv/DetectCalibrationPattern.srv#L2

is ignored in the following function
https://github.com/delftrobotics/dr_ensenso/blob/master/dr_ensenso_node/src/ensenso.cpp#L318

which makes it really hard to recalibrate after the very first time calibrating an ensenso.

Issue is easily fixed by adding req.ignore_calibration in the call to the library function in this line:
https://github.com/delftrobotics/dr_ensenso/blob/master/dr_ensenso_node/src/ensenso.cpp#L325

**Comment by de-vri-es** [comment]
Ah, good catch. Could you file a PR?
